# Generated by Django 5.2.5 on 2025-08-25 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва звання')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Військове звання',
                'verbose_name_plural': 'Військові звання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Serviceman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='Місце народження')),
                ('tax_id_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='РНОКПП')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Номер документа, що посвідчує особу')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='servicemen_photos/', verbose_name='Фото')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffing.position', verbose_name='Посада')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.rank', verbose_name='Військове звання')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обліковий запис')),
            ],
            options={
                'verbose_name': 'Військовослужбовець',
                'verbose_name_plural': 'Військовослужбовці',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APPOINTMENT', 'Призначення'), ('TRANSFER', 'Переведення'), ('PROMOTION', 'Підвищення у званні'), ('DISMISSAL', 'Звільнення')], max_length=20, verbose_name='Тип події')),
                ('event_date', models.DateField(verbose_name='Дата події')),
                ('details', models.JSONField(default=dict, help_text='Зберігає деталі, напр. new_rank, new_position', verbose_name='Деталі')),
                ('order_reference', models.CharField(max_length=255, verbose_name='Посилання на наказ')),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='personnel.serviceman')),
            ],
            options={
                'verbose_name': 'Подія в історії служби',
                'verbose_name_plural': 'Історія служби',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата укладення контракту')),
                ('end_date', models.DateField(verbose_name='Дата закінчення контракту')),
                ('details', models.TextField(blank=True, verbose_name='Деталі контракту')),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='personnel.serviceman')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракти',
                'ordering': ['-start_date'],
            },
        ),
    ]
