# Generated by Django 5.2.5 on 2025-08-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceman',
            name='status',
            field=models.CharField(choices=[('ON_DUTY', 'На службі'), ('ON_LEAVE', 'У відпустці'), ('SICK_LEAVE', 'На лікуванні'), ('AWOL', 'СЗЧ'), ('DISMISSED', 'Звільнено'), ('KIA', 'Загинув'), ('MIA', 'Зник безвісти')], default='ON_DUTY', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='servicehistoryevent',
            name='event_type',
            field=models.CharField(choices=[('ENLISTMENT', 'Зарахування на службу'), ('APPOINTMENT', 'Призначення на посаду'), ('TRANSFER', 'Переведення'), ('PROMOTION', 'Підвищення у званні'), ('DISMISSAL', 'Звільнення'), ('DEATH', 'Загибель/Смерть')], max_length=20, verbose_name='Тип події'),
        ),
    ]
