# Generated by Django 5.2.5 on 2025-08-26 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_serviceman_status_and_more'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата призначення')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата звільнення з посади')),
                ('order_reference', models.CharField(max_length=255, verbose_name='Посилання на наказ')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffing.position', verbose_name='Посада')),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='personnel.serviceman', verbose_name='Військовослужбовець')),
            ],
            options={
                'verbose_name': 'Історія посад',
                'verbose_name_plural': 'Історії посад',
                'ordering': ['-start_date'],
            },
        ),
    ]
