# Generated by Django 5.2.5 on 2025-08-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_positionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceman',
            name='enlistment_authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='Орган, що здійснив призов (прийняття)'),
        ),
        migrations.AddField(
            model_name='serviceman',
            name='enlistment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата призову (прийняття) на службу'),
        ),
        migrations.AddField(
            model_name='serviceman',
            name='personal_number',
            field=models.CharField(blank=True, help_text='Відповідає РНОКПП або серії та номеру паспорта', max_length=20, null=True, unique=True, verbose_name='Особистий номер (ідентифікаційний жетон)'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SECONDARY', 'Повна загальна середня'), ('VOCATIONAL', 'Професійно-технічна'), ('JUNIOR_COLLEGE', 'Фахова передвища'), ('BACHELOR', 'Бакалавр'), ('MASTER', 'Магістр'), ('PHD', 'Доктор філософії')], max_length=20, verbose_name='Рівень освіти')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Назва навчального закладу')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Рік закінчення')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Спеціальність')),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='personnel.serviceman')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('WIFE', 'Дружина'), ('HUSBAND', 'Чоловік'), ('SON', 'Син'), ('DAUGHTER', 'Донька'), ('FATHER', 'Батько'), ('MOTHER', 'Мати'), ('OTHER', 'Інше')], max_length=20, verbose_name='Ступінь споріднення')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса проживання')),
                ('serviceman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='personnel.serviceman')),
            ],
            options={
                'verbose_name': "Член сім'ї",
                'verbose_name_plural': "Члени сім'ї",
            },
        ),
    ]
