# Generated by Django 5.2.5 on 2025-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_serviceman_enlistment_authority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('rank_name', models.CharField(max_length=100, verbose_name='Військове звання')),
                ('position_name', models.CharField(max_length=255, verbose_name='Посада')),
                ('origin_unit', models.CharField(max_length=255, verbose_name='Звідки прибув (в/ч, населений пункт)')),
                ('arrival_reason', models.CharField(max_length=255, verbose_name='Підстава прибуття (наказ, розпорядження)')),
                ('arrival_date', models.DateField(verbose_name='Дата прибуття')),
                ('arrival_order', models.CharField(blank=True, max_length=100, verbose_name='Наказ про прибуття (дата і номер)')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата вибуття')),
                ('departure_order', models.CharField(blank=True, max_length=100, verbose_name='Наказ про вибуття (дата і номер)')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткова інформація')),
            ],
            options={
                'verbose_name': 'Тимчасово прибулий',
                'verbose_name_plural': '4. Тимчасово прибулі',
                'ordering': ['-arrival_date'],
            },
        ),
    ]
