# Generated by Django 5.2.5 on 2025-08-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_temporaryarrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrecoverableLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_type', models.CharField(choices=[('KIA', 'Загинув'), ('DIED', 'Помер (від хвороби, нещасного випадку)'), ('MIA', 'Зник безвісти'), ('CAPTURED', 'Полонений')], max_length=10, verbose_name='Вид втрати')),
                ('loss_date', models.DateField(verbose_name='Дата безповоротної втрати')),
                ('circumstances', models.TextField(verbose_name='Обставини, що призвели до втрати')),
                ('loss_location', models.CharField(max_length=255, verbose_name='Місце втрати')),
                ('exclusion_date', models.DateField(verbose_name='Дата виключення зі списків')),
                ('exclusion_order', models.CharField(max_length=100, verbose_name='Наказ про виключення (дата і номер)')),
                ('notification_details', models.CharField(blank=True, max_length=255, verbose_name='Кому, за яким номером і коли надіслано сповіщення')),
                ('burial_location', models.CharField(blank=True, max_length=255, verbose_name='Місце і дата поховання (імовірне місце перебування)')),
                ('serviceman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loss_record', to='personnel.serviceman', verbose_name='Військовослужбовець')),
            ],
            options={
                'verbose_name': 'Безповоротна втрата',
                'verbose_name_plural': '7. Безповоротні втрати',
                'ordering': ['-loss_date'],
            },
        ),
    ]
