# Generated by Django 5.2.5 on 2025-08-26 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер наказу')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('order_type', models.CharField(choices=[('PERSONNEL', 'По особовому складу'), ('SERVICE', 'По стройовій частині')], max_length=20, verbose_name='Тип наказу')),
                ('issuing_authority', models.CharField(max_length=255, verbose_name='Орган, що видав наказ')),
                ('status', models.CharField(choices=[('DRAFT', 'Проєкт'), ('ON_APPROVAL', 'На погодженні'), ('SIGNED', 'Підписано'), ('EXECUTED', 'Виконано'), ('CANCELED', 'Скасовано')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('order_text', models.TextField(blank=True, verbose_name='Повний текст наказу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Наказ',
                'verbose_name_plural': 'Накази',
                'ordering': ['-order_date', '-order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPOINT', 'Призначити'), ('TRANSFER', 'Перевести'), ('PROMOTE', 'Присвоїти звання'), ('DISMISS', 'Звільнити'), ('AWARD', 'Нагородити'), ('REPRIMAND', 'Оголосити догану'), ('EXCLUDE_KIA', 'Виключити як загиблого')], max_length=20, verbose_name='Тип дії')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Зберігає контекстно-залежні дані, наприклад, ID нової посади для призначення', verbose_name='Деталі дії')),
                ('execution_status', models.BooleanField(default=False, verbose_name='Статус виконання')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='orders.order', verbose_name='Наказ')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_actions', to='personnel.serviceman', verbose_name='Особа')),
            ],
            options={
                'verbose_name': 'Дія за наказом',
                'verbose_name_plural': 'Дії за наказами',
                'ordering': ['order'],
            },
        ),
    ]
