# Generated by Django 5.2.5 on 2025-08-25 09:47

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitarySpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код ВОС')),
                ('name', models.CharField(max_length=255, verbose_name='Найменування')),
            ],
            options={
                'verbose_name': 'Військово-облікова спеціальність',
                'verbose_name_plural': 'Військово-облікові спеціальності',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Найменування підрозділу')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='staffing.unit', verbose_name='Вищий підрозділ')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_index', models.CharField(max_length=50, unique=True, verbose_name='Індекс посади')),
                ('name', models.CharField(max_length=255, verbose_name='Найменування посади')),
                ('category', models.CharField(max_length=100, verbose_name='Штатно-посадова категорія')),
                ('tariff_rate', models.CharField(max_length=50, verbose_name='Тарифний розряд')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffing.militaryspecialty', verbose_name='Військово-облікова спеціальність')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='staffing.unit', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
                'ordering': ['name'],
            },
        ),
    ]
