# Generated by Django 5.2.5 on 2025-08-28 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_serviceman_enlistment_authority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicemanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Номер, що присвоюється при реєстрації в частині', max_length=100, unique=True, verbose_name='Реєстраційний номер')),
                ('submission_date', models.DateField(verbose_name='Дата подання')),
                ('report_type', models.CharField(choices=[('LEAVE', 'Рапорт на відпустку'), ('TRANSFER', 'Рапорт на переведення'), ('DISMISSAL', 'Рапорт на звільнення'), ('FINANCIAL', 'Фінансовий рапорт'), ('MATERIAL', 'Рапорт на матеріальне забезпечення'), ('OTHER', 'Інший рапорт')], max_length=20, verbose_name='Тип рапорту')),
                ('status', models.CharField(choices=[('DRAFT', 'Проєкт'), ('SUBMITTED', 'Подано'), ('UNDER_REVIEW', 'На розгляді'), ('APPROVED', 'Затверджено'), ('REJECTED', 'Відхилено'), ('ARCHIVED', 'В архіві')], default='SUBMITTED', max_length=20, verbose_name='Статус')),
                ('recipient_position', models.CharField(help_text="Наприклад, 'Командиру 1-ї механізованої роти'", max_length=255, verbose_name='Посада отримувача')),
                ('summary', models.CharField(max_length=255, verbose_name='Короткий зміст (тема)')),
                ('full_text', models.TextField(blank=True, verbose_name='Повний текст рапорту')),
                ('resolution', models.TextField(blank=True, verbose_name='Резолюція / Рішення по рапорту')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='personnel.serviceman', verbose_name='Автор рапорту')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Хто розглянув')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорти військовослужбовців',
                'ordering': ['-submission_date'],
            },
        ),
    ]
