# Generated by Django 5.2.5 on 2025-08-28 14:17

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanreport',
            name='attachment',
            field=models.FileField(blank=True, help_text='Додайте скан-копію рапорту або інші супровідні документи', null=True, upload_to=apps.documents.models.report_attachment_path, verbose_name='Прикріплений файл'),
        ),
    ]
