# Generated by Django 5.2.5 on 2025-08-27 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час експорту')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('JSON', 'JSON'), ('XML', 'XML')], max_length=10, verbose_name='Формат')),
                ('records_count', models.PositiveIntegerField(verbose_name='Кількість записів')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='Застосовані фільтри')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Шлях до файлу')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог експорту даних',
                'verbose_name_plural': 'Логи експорту даних',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Успішний вхід'), ('LOGIN_FAILED', 'Невдалий вхід'), ('PASSWORD_CHANGE', 'Зміна пароля'), ('PASSWORD_RESET', 'Скидання пароля'), ('PERMISSION_DENIED', 'Відмова в доступі'), ('SUSPICIOUS_ACTIVITY', 'Підозріла активність'), ('DATA_EXPORT', 'Експорт даних'), ('BULK_OPERATION', 'Масова операція')], max_length=30, verbose_name='Тип події')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час події')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адреса')),
                ('details', models.JSONField(default=dict, verbose_name='Деталі')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Вирішено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Час вирішення')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Примітки до вирішення')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL, verbose_name='Вирішено користувачем')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Подія безпеки',
                'verbose_name_plural': 'Події безпеки',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Створено'), ('UPDATE', 'Оновлено'), ('DELETE', 'Видалено'), ('VIEW', 'Переглянуто'), ('EXPORT', 'Експортовано'), ('LOGIN', 'Вхід в систему'), ('LOGOUT', 'Вихід з системи'), ('PERMISSION_CHANGE', 'Зміна прав доступу')], max_length=20, verbose_name='Дія')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Час події')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID об'єкта")),
                ('object_repr', models.CharField(help_text="Текстове представлення об'єкта на момент дії", max_length=255, verbose_name="Представлення об'єкта")),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON з старими та новими значеннями', verbose_name='Зміни')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сесії')),
                ('severity', models.CharField(choices=[('INFO', 'Інформація'), ('WARNING', 'Попередження'), ('ERROR', 'Помилка'), ('CRITICAL', 'Критично')], default='INFO', max_length=10, verbose_name='Важливість')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Тип об'єкта")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Журнал аудиту',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditing_au_timesta_6ab1d7_idx'), models.Index(fields=['user', '-timestamp'], name='auditing_au_user_id_35da21_idx'), models.Index(fields=['action', '-timestamp'], name='auditing_au_action_b1119e_idx'), models.Index(fields=['content_type', 'object_id'], name='auditing_au_content_ce594f_idx')],
            },
        ),
    ]
